M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date Sun Apr 16 17:58:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-16T17:58:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X132.5Y-91.5
X150.5Y-91.5
T0
M30
